server:
  port: 8099
spring:
  profiles:
    active: dev
  application:
    name: @pom.artifactId@
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/plaza-oauth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
